mv ./visage.navigation/src/org/netbeans/modules/javafx ./visage.navigation/src/org/netbeans/modules/visage
mv ./visage.palette/src/org/netbeans/modules/javafx ./visage.palette/src/org/netbeans/modules/visage
mv ./visage.platform/probesrc/org/netbeans/modules/javafx ./visage.platform/probesrc/org/netbeans/modules/visage
mv ./visage.platform/src/org/netbeans/api/javafx ./visage.platform/src/org/netbeans/api/visage
mv ./visage.platform/src/org/netbeans/modules/javafx ./visage.platform/src/org/netbeans/modules/visage
mv ./visage.platform/test/unit/src/org/netbeans/modules/javafx ./visage.platform/test/unit/src/org/netbeans/modules/visage
mv ./visage.profiler/src/org/netbeans/modules/javafx ./visage.profiler/src/org/netbeans/modules/visage
mv ./visage.project/src/org/netbeans/modules/javafx ./visage.project/src/org/netbeans/modules/visage
mv ./visage.project/test/unit/src/org/netbeans/modules/javafx ./visage.project/test/unit/src/org/netbeans/modules/visage
mv ./visage.refactoring/src/org/netbeans/modules/javafx ./visage.refactoring/src/org/netbeans/modules/visage
mv ./visage.refactoring/src/org/netbeans/modules/javafx/refactoring/impl/javafxc ./visage.refactoring/src/org/netbeans/modules/javafx/refactoring/impl/javafxc
mv ./visage.refactoring/test/unit/data/goldenfiles/org/netbeans/modules/javafx ./visage.refactoring/test/unit/data/goldenfiles/org/netbeans/modules/visage
mv ./visage.refactoring/test/unit/data/org/netbeans/api/javafx ./visage.refactoring/test/unit/data/org/netbeans/api/visage
mv ./visage.refactoring/test/unit/data/org/netbeans/modules/javafx ./visage.refactoring/test/unit/data/org/netbeans/modules/visage
mv ./visage.refactoring/test/unit/src/org/netbeans/modules/javafx ./visage.refactoring/test/unit/src/org/netbeans/modules/visage
mv ./visage.runtime/src/org/netbeans/modules/javafx ./visage.runtime/src/org/netbeans/modules/visage
mv ./visage.sdk.lin/src/org/netbeans/modules/javafx ./visage.sdk.lin/src/org/netbeans/modules/visage
mv ./visage.sdk.mac/src/org/netbeans/modules/javafx ./visage.sdk.mac/src/org/netbeans/modules/visage
mv ./visage.sdksamples/javafx.sdksamples ./visage.sdksamples/javafx.sdksamples
mv ./visage.sdksamples/javafx.sdksamples/src/org/netbeans/modules/javafx ./visage.sdksamples/javafx.sdksamples/src/org/netbeans/modules/visage
mv ./visage.sdk.sol/src/org/netbeans/modules/javafx ./visage.sdk.sol/src/org/netbeans/modules/visage
mv ./visage.sdk.win/src/org/netbeans/modules/javafx ./visage.sdk.win/src/org/netbeans/modules/visage
mv ./visage.source/src/org/netbeans/api/javafx ./visage.source/src/org/netbeans/api/visage
mv ./visage.source/src/org/netbeans/modules/javafx ./visage.source/src/org/netbeans/modules/visage
mv ./visage.source/test/unit/data/org/netbeans/api/javafx ./visage.source/test/unit/data/org/netbeans/api/visage
mv ./visage.source/test/unit/src/org/netbeans/api/javafx ./visage.source/test/unit/src/org/netbeans/api/visage
mv ./visage.weather2/src/org/netbeans/modules/javafx ./visage.weather2/src/org/netbeans/modules/visage
mv ./visage.weather2/test/qa-functional/src/org/netbeans/test/javafx ./visage.weather2/test/qa-functional/src/org/netbeans/test/visage
