/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VaribleCellrenderer.java
 *
 * Created on Jun 7, 2010, 10:41:18 AM
 */

package org.netbeans.modules.javafx.debugger.tablerendering;

import com.sun.javafx.jdi.FXField;
import com.sun.javafx.jdi.FXValue;
import com.sun.javafx.jdi.FXIntegerValue;
import com.sun.javafx.jdi.FXSequenceReference;
import com.sun.jdi.Value;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.TableCellRenderer;
import org.netbeans.api.debugger.jpda.Field;
import org.netbeans.modules.debugger.jpda.expr.JDIVariable;

/**
 *
 * @author Michal Skvor <michal.skvor at sun.com>
 */
public class VariableCellRenderer extends javax.swing.JPanel implements TableCellRenderer {

    private static final boolean evaluateImmediate = false;

    private Object o;
    private String columnName;

    /** Creates new form VaribleCellrenderer */
    public VariableCellRenderer( Object o, String columnName ) {
        this.o = o;
        this.columnName = columnName;
        
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        labelValue = new javax.swing.JLabel();
        buttonUpdate = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        labelValue.setBackground(javax.swing.UIManager.getDefaults().getColor("Table.focusCellBackground"));
        labelValue.setText(org.openide.util.NbBundle.getMessage(VariableCellRenderer.class, "VariableCellRenderer.labelValue.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.ABOVE_BASELINE;
        gridBagConstraints.weightx = 1.0;
        add(labelValue, gridBagConstraints);

        buttonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/netbeans/modules/javafx/debugger/resources/redo.png"))); // NOI18N
        buttonUpdate.setText(org.openide.util.NbBundle.getMessage(VariableCellRenderer.class, "VariableCellRenderer.buttonUpdate.text")); // NOI18N
        buttonUpdate.setToolTipText(org.openide.util.NbBundle.getMessage(VariableCellRenderer.class, "VariableCellRenderer.buttonUpdate.toolTipText")); // NOI18N
        buttonUpdate.setMaximumSize(new java.awt.Dimension(32, 32));
        buttonUpdate.setMinimumSize(new java.awt.Dimension(32, 20));
        buttonUpdate.setPreferredSize(new java.awt.Dimension(32, 32));
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        add(buttonUpdate, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
        System.out.println(" - updating variable");
        labelValue.setText( "Updating" );
    }//GEN-LAST:event_buttonUpdateActionPerformed

    public Component getTableCellRendererComponent( JTable table, Object value,
            boolean isSelected, boolean hasFocus, int row, int column )
    {
        if( o instanceof Field ) {
            Field f = (Field)o;
            JDIVariable v = (JDIVariable)f;
            Value oo = v.getJDIValue();
            FXValue fxv = (FXValue)oo;
            oo.virtualMachine().classesByName( fxv.type().name());

            FXField fxf = (FXField)oo.virtualMachine().classesByName( f.getClassName()).get( 0 ).fieldByName( f.getName());
            boolean bound = fxf.declaringType().isBound( fxf );
            boolean invalid = fxf.declaringType().isInvalid( fxf );

            if(!( invalid || bound ) || evaluateImmediate ) {
                labelValue.setText( f.getValue());
                if( fxv instanceof FXSequenceReference ) {
                    FXSequenceReference ref = (FXSequenceReference)fxv;
                    labelValue.setText( labelValue.getText() + "(length= " + ref.length() + ")" );
                }
                buttonUpdate.setVisible( false );
            } else {
                labelValue.setText( "Invalid value" );
                buttonUpdate.setVisible( true );
            }
        } else {
            labelValue.setText( value.toString());
        }
        if( isSelected ) {
            setBackground( UIManager.getDefaults().getColor( "Table.selectionBackground" ));
            setForeground( UIManager.getDefaults().getColor( "Table.selectionForeground" ));
            labelValue.setBackground( UIManager.getDefaults().getColor( "Table.selectionBackground" ));
            labelValue.setForeground( UIManager.getDefaults().getColor( "Table.selectionForeground" ));
        } else {
            setBackground( UIManager.getDefaults().getColor( "Table.focusCellBackground" ));
            setForeground( UIManager.getDefaults().getColor( "Table.focusCellForeground" ));
            labelValue.setBackground( UIManager.getDefaults().getColor( "Table.focusCellBackground" ));
            labelValue.setForeground( UIManager.getDefaults().getColor( "Table.focusCellForeground" ));
        }

        return this;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JLabel labelValue;
    // End of variables declaration//GEN-END:variables

}
