/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VariableCellEditor.java
 *
 * Created on Jun 8, 2010, 10:03:56 AM
 */

package org.netbeans.modules.javafx.debugger.tablerendering;

import java.awt.Component;
import java.util.EventObject;
import javax.swing.JTable;
import javax.swing.event.CellEditorListener;
import javax.swing.table.TableCellEditor;

/**
 *
 * @author Michal Skvor <michal.skvor at sun.com>
 */
public class VariableCellEditor extends javax.swing.JPanel implements TableCellEditor {

    /** Creates new form VariableCellEditor */
    public VariableCellEditor( Object o ) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTextField1 = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jTextField1.setText(org.openide.util.NbBundle.getMessage(VariableCellEditor.class, "VariableCellEditor.jTextField1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        add(jTextField1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public Component getTableCellEditorComponent( JTable table, Object value, boolean isSelected, int row, int column ) {
        return this;
    }

    public Object getCellEditorValue() {
        return 0;
    }

    public boolean isCellEditable( EventObject anEvent ) {
        return false;
    }

    public boolean shouldSelectCell( EventObject anEvent ) {
        return false;
    }

    public boolean stopCellEditing() {
        return true;
    }

    public void cancelCellEditing() {
    }

    public void addCellEditorListener( CellEditorListener l ) {
    }

    public void removeCellEditorListener( CellEditorListener l ) {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
